<a href="https://colab.research.google.com/github/SYEON9/natural_language_3th/blob/main/HW/%5BDL01%5DPyTorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#import Package

필요한 package를 설치하고 import하자. 
GPU를 사용할 것이므로 torch.cuda.is_avialable()이 True가 나와야 한다. 

In [3]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

1.10.0+cu111
True


In [4]:
#나머지 패키지를 불러오자
import matplotlib.pyplot as plt
import numpy as np
import scipy as sp

np.set_printoptions(precision=3)   #numpy 객체가 표시되는 방식 결정
np.set_printoptions(suppress = True)    #고정소수점 표기법 사용.

#tensor operations

텐서는 array나 matrix와 매우 유사한 특수 자료구조이다. PyTorch에서는 텐서를 사용하여 모델의 입력과 출력뿐만 아니라 모델의 파라미터를 나타낸다. 
텐서는 NumPy의 ndarray와 매우 유사하지만 GPU나 다른 연산 가속을 위한 특수한 하드웨어에서 실행할 수 있다. 

#텐서 초기화하기
데이터로부터 직접 생성하기


In [6]:
data = [[1,2],[3,4]]
x = torch.tensor(data)    #tensor 생성
x

tensor([[1, 2],
        [3, 4]])

Numpy array로부터 생성하기


In [7]:
np_array = np.array(data)
x = torch.tensor(np_array)   #ndarray를 torch.tensor로 변환가능.
x

tensor([[1, 2],
        [3, 4]])

Tensor에서 Numpy array로 변환하기


In [8]:
x.numpy()

array([[1, 2],
       [3, 4]])

다른 텐서와 같은 모양의 텐서 초기화하기

In [12]:
x_ones = torch.ones_like(x)    #x_data의 속성을 유지한다. 1로 채워진 텐서를 x 크기로 반환한다. 
print(f"Ones Tensor: \n {x_ones} \n")    #x의 원소가 int형이므로 int형으로 만듬.

x_rand = torch.rand_like(x, dtype = torch.float)   #x_data의 속성을 덮어씁니다. 0~1사이의 무작위 값이 채워진 x크기의 tensor를 반환한다. 
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6593, 0.9410],
        [0.9785, 0.6666]]) 



주어진 shape으로 초기화하기

In [17]:
shape = (3, 4)                   #원소의 기본형은 float
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1940, 0.2303, 0.2951, 0.6549],
        [0.5364, 0.9793, 0.4207, 0.8655],
        [0.1990, 0.5442, 0.6833, 0.0841]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


#텐서의 속성

텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타낸다.

In [18]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


cpu에 할당되어 있는 tensor를 GPU에 옮길 수 있다.

In [19]:
device = torch.device('cuda')
tensor = tensor.to(device)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


#텐서 연산
numpy 식의 인덱싱과 슬라이싱

In [21]:
tensor = torch.ones(3,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


텐서 합치기

In [23]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)   #행을 기준으로 tensor 합치기
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [24]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


텐서 곱하기

In [25]:
#요소별 곱(element - wise product)을 계산한다.
print(f"Tensor.mul(tensor) \n {tensor.mul(tensor)} \n")

#다른 문법
print(f"tensor * tensor \n {tensor * tensor}")

Tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


텐서간 matrix multiplication 진행하기


In [28]:
#두 텐서의 행렬 곱 구하기
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")

#다른 문법:직접 곱하기
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


#Autograd

PyTorch에는 torch.autograd라고 불리는 자동 미분 엔진이 내장되어 있다. 이는 모든 node에 대한 미분값을 자동으로 계산해준다.
input X, params W, 그리고 cross-entropy loss를 사용하는 logistic regression model의 gradient를 autograd를 이용해서 구해보자.

#input 및 params 초기화

In [29]:
x = torch.ones(5)     #input tensor
y = torch.zeros(3)    #expected output
w = torch.randn(5,3, requires_grad = True)   #rand()가 0~1사이의 값으로 변환되는 것과 달리 평균이 0인 평균 분포로 나타낸다. 
b = torch.randn(3, requires_grad = True)

print(x)
print(y)
print(w)
print(b)


tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0.])
tensor([[-1.7750,  0.1882, -0.1376],
        [ 2.3293,  0.5629,  1.0354],
        [ 0.5014,  0.9516, -0.0618],
        [-0.1594,  0.1861,  0.6967],
        [ 1.4305,  0.7148, -0.6754]], requires_grad=True)
tensor([ 0.7050,  1.7429, -1.1013], requires_grad=True)


#Forward

In [30]:
z = torch.matmul(x, w) + b
z

tensor([ 3.0318,  4.3465, -0.2441], grad_fn=<AddBackward0>)

#Loss Function
Pytorch에서는 node를 크게 2가지의 방법으로 api를 활용해서 사용한다. 
1. torch.nn
2. torch.nn.functional


torch.nn은 사전에 node를 초기화 시켜두고, 해당 node에 텐서를 통과시켜 값을 받는 형태이다. 그러나 torch.nn.functional은 사전에 초기화없이 바로 함수처럼 사용하는 방식이다. 

코딩 스타일에 맞춰 원하는 api를 선택해 사용하면 된다.

In [31]:
loss_fn = torch.nn.BCEWithLogitsLoss()
loss = loss_fn(z, y)
loss

tensor(2.6723, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [32]:
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)
loss

tensor(2.6723, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

#Backward
모델에서 배개변수의 가중치를 최적화하려면 파라미터에 대한 loss function의 도함수를 계산해야 한다. 이런 도함수를 계산하기 위해, loss.backward()를 호출한 다음 w.grad와 b.grad에서 값을 가져온다. 

In [33]:
loss.backward()
print(x.grad)
print(w.grad)
print(b.grad)

None
tensor([[0.3180, 0.3291, 0.1464],
        [0.3180, 0.3291, 0.1464],
        [0.3180, 0.3291, 0.1464],
        [0.3180, 0.3291, 0.1464],
        [0.3180, 0.3291, 0.1464]])
tensor([0.3180, 0.3291, 0.1464])


기본적으로, requires_grad = True인 모든 텐서들은 연산 기록을 추적하고 미분 계산을 지원한다. 그러나 모델을 학습한 뒤 입력 데이터를 단순히 적용하기만 하는 경우와 같이 forward 연산만 필요한 경우에는, 미분 연산을 위한 값들을 저장해두는 것이 속력 및 메모리의 저하를 가져올 수 있따. 연산 코드를 torch.no_grad()블록으로 둘러싸서 미분 추적을 멈출 수 있다.

In [34]:
z = torch.matmul(x, w) + b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False
